if(NOT APP_RENDER_SYSTEM OR APP_RENDER_SYSTEM STREQUAL "gl")
 set(APP_RENDER_SYSTEM gles)
endif()

set(PLATFORM_REQUIRED_DEPS OpenGLES EGL CedarDisplay VDPAU_SUNXI CedarAccess UMP LibInput Xkbcommon)
set(PLATFORM_OPTIONAL_DEPS CedarJpeg)
#list(APPEND ARCH_DEFINES -DALLWINNERA10)
#list(APPEND ARCH_DEFINES -DUSE_VIDEO_SYNC_FB)
