set(PLATFORM_REQUIRED_DEPS OpenGLES EGL CedarDisplay VdpauSunxi CedarAccess UMP VDPAU LibInput Xkbcommon)
set(PLATFORM_OPTIONAL_DEPS CedarJpeg)
list(APPEND PLATFORM_DEFINES -DALLWINNERA10)
list(APPEND PLATFORM_DEFINES -DUSE_VIDEO_SYNC_FB)
